language: python
python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python3
  - pip install coverage
  - pip install codecov
  - pip3 install mypy-lang

install:
  - "pip install -r requirements-dev.txt"

script:
  - "mypy --py2 --silent-imports navdoon"
  - "./run-test-coverage.py"

after_success:
  - codecov

notifications:
  email: false

