from typing import AnyStr, List, Iterable, Tuple
from navdoon.utils import TCPClient

Lines = List[AnyStr]
Metrics = Iterable[Tuple(AnyStr, float, float)]

class Graphite(TCPClient):
    def __init__(self, host: AnyStr, port: int) -> None: ...
    def __del__(self) -> None: ...
    @staticmethod
    def create_request_from_metrics(metrics: Iterable[Tuple(AnyStr, float, float)]) -> Lines: ...
    def flush(self, metrics: Metrics) -> None: ...
    def _send_lines(self, lines: Lines) -> None: ...