from typing import AnyStr, List, Tuple
from navdoon.utils.common import TCPClient
from navdoon.destination.abstract import AbstractDestination

Lines = List[AnyStr]
Metrics = List[Tuple[AnyStr, float, float]]


class Graphite(TCPClient, AbstractDestination):
    def __init__(self, host: AnyStr, port: int) -> None: ...
    def __del__(self) -> None: ...
    @staticmethod
    def create_request_from_metrics(metrics: Metrics) -> Lines: ...
    def flush(self, metrics: Metrics) -> None: ...
    def _send_lines(self, lines: Lines) -> None: ...
