from typing import List, AnyStr, Tuple, io, Iterable

Metrics = Iterable[Tuple(AnyStr, float, float)]
Lines = List[AnyStr]

class Stream(object):
    def __init__(self, file_handle: io) -> None: ...
    def create_output_from_metrics(self, metrics: Metrics) -> Lines: ...
    def flush(self, metrics: Metrics) -> None: ...
    def _write_lines(self, lines: Lines) -> None: ...


class Stdout(Stream):
    def __init__(self) -> None: ...